# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure Functions: https://aka.ms/python-webapps-actions

name: Function-CICD

on:

  workflow_dispatch:
    inputs:
      # This is the path of your Azure Function in Git.  
      GIT_FunctionApp_Name:
        description: 'Provide the Function App Name'
        required: true
        default: 'rohini-testingfunctionapp'
        
      GIT_FunctionApp_URL:
        description: 'Provide the Function App URL'
        required: true
        default: 'https://rohini-testingfunctionapp.azurewebsites.net'
        
       # This is the path of your Function app in Git.
      GIT_FunctionApp_PATH:
        description: 'Relative path for Function'
        required: true
        default: '/FunctionApp/DemoSample/'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AZURE_FUNCTIONAPP_PACKAGE_PATH: ${{ github.workspace }}/${{ github.event.inputs.GIT_FunctionApp_PATH }} # set this to the path to your web app project, defaults to the repository root
      PYTHON_VERSION: '3.7' # set this to the python version to use (supports 3.6, 3.7, 3.8)
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python version
        uses: actions/setup-python@v1
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      #Install All the Required Depenedent Modules
      - name: Install dependencies
        run: |
          pushd $GITHUB_WORKSPACE/${{ github.event.inputs.GIT_FunctionApp_PATH }}
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"
          popd
          
      - name: 'Run Azure Functions action'
      uses: Azure/functions-action@v1
      with:
          app-name: ${{ github.event.inputs.GIT_FunctionApp_Name }}
          package: ${{ github.workspace }}/${{ github.event.inputs.GIT_FunctionApp_PATH }}
          publish-profile: ${{ secrets.FUNCTIONAPP_PUBLISH }}
